-- Optional manual schema for sombat-tour APIs (also auto-created by ensure_schema)
-- Run once on MySQL if ALTER permissions are restricted for the web user.

CREATE TABLE IF NOT EXISTS app_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  pin_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'viewer',
  department VARCHAR(128) DEFAULT '',
  token VARCHAR(64) DEFAULT NULL,
  token_expires DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS repair_image (
  id INT AUTO_INCREMENT PRIMARY KEY,
  r_id INT NOT NULL,
  path VARCHAR(512) NOT NULL,
  uploaded_by VARCHAR(128) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (r_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS board (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT,
  department VARCHAR(128) DEFAULT '',
  color VARCHAR(32) DEFAULT '#FFF59D',
  pin TINYINT(1) DEFAULT 0,
  created_by VARCHAR(128) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vehicle_location (
  id INT AUTO_INCREMENT PRIMARY KEY,
  v_id INT DEFAULT NULL,
  v_name VARCHAR(128) DEFAULT '',
  title VARCHAR(255) NOT NULL,
  detail TEXT,
  spot VARCHAR(255) DEFAULT '',
  created_by VARCHAR(128) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (v_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Optional columns on existing repair table:
-- ALTER TABLE repair ADD COLUMN r_technician_id INT DEFAULT NULL;
-- ALTER TABLE repair ADD COLUMN r_type VARCHAR(32) DEFAULT 'normal';
-- ALTER TABLE repair ADD COLUMN r_tank_m VARCHAR(64) DEFAULT NULL;
